<!--Licensed to the Apache Software Foundation (ASF) under one or more contributor 
	license agreements. See the NOTICE file distributed with this work for additional 
	information regarding copyright ownership. The ASF licenses this file to 
	you under the Apache License, Version 2.0 (theÏ "License"); you may not use 
	this file except in compliance with the License. You may obtain a copy of 
	the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required 
	by applicable law or agreed to in writing, software distributed under the 
	License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS 
	OF ANY ~ KIND, either express or implied. See the License for the specific 
	language governing permissions and limitations under the License. -->

<!DOCTYPE assembly [
        <!ELEMENT assembly (id|includeBaseDirectory|baseDirectory|formats|fileSets|dependencySets)*>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT includeBaseDirectory (#PCDATA)>
        <!ELEMENT baseDirectory (#PCDATA)>
        <!ELEMENT formats (format)*>
        <!ELEMENT format (#PCDATA)>
        <!ELEMENT fileSets (fileSet)*>
        <!ELEMENT fileSet (directory|outputDirectory|includes)*>
        <!ELEMENT directory (#PCDATA)>
        <!ELEMENT outputDirectory (#PCDATA)>
        <!ELEMENT includes (include)*>
        <!ELEMENT include (#PCDATA)>
        <!ELEMENT dependencySets (dependencySet)*>
        <!ELEMENT dependencySet (outputDirectory|includes)*>
        ]>
<assembly>
	<id>bin</id>
	<includeBaseDirectory>true</includeBaseDirectory>
	<baseDirectory>${archieve.name}-${version}</baseDirectory>
	<formats>
		<format>tar.gz</format>
		<format>zip</format>
	</formats>

	<fileSets>

		<!-- ********************** copy release notes files ********************** -->
		<fileSet>
			<directory>../../../</directory>
			<outputDirectory>.</outputDirectory>
			<includes>
				<include>RELEASE_NOTES</include>
			</includes>
		</fileSet>
		<!-- ********************** copy licenses, readme etc. ********************** -->
		<fileSet>
			<directory>src/main/resources/</directory>
			<outputDirectory>.</outputDirectory>
			<includes>
				<include>LICENSE</include>
				<include>NOTICE</include>
				<include>README</include>
				<include>INSTALL</include>
			</includes>
		</fileSet>

		<!-- ********************** copy database scripts ********************** -->
		<fileSet>
			<directory>../../ws-messenger/messagebroker/src/main/resources/database_scripts
			</directory>
			<outputDirectory>bin/database_scripts
			</outputDirectory>
			<includes>
				<include>*sql*</include>
			</includes>
		</fileSet>
		<fileSet>
			<directory>../../ws-messenger/messagebox/src/main/resources/database_scripts
			</directory>
			<outputDirectory>bin/database_scripts
			</outputDirectory>
			<includes>
				<include>*sql*</include>
			</includes>
		</fileSet>
		<fileSet>
			<directory>../../registry/airavata-jpa-registry/src/main/resources
			</directory>
			<outputDirectory>bin/database_scripts
			</outputDirectory>
			<includes>
				<include>*sql*</include>
			</includes>
		</fileSet>
		<fileSet>
			<directory>../../app-catalog/app-catalog-data/src/main/resources
			</directory>
			<outputDirectory>bin/database_scripts
			</outputDirectory>
			<includes>
				<include>*sql*</include>
			</includes>
		</fileSet>
		<fileSet>
			<directory>src/main/resources/bin</directory>
			<outputDirectory>bin</outputDirectory>
			<fileMode>777</fileMode>
			<includes>
				<include>*.sh</include>
				<include>*.bat</include>
				<include>logo.txt</include>
				<include>startNetworkServer</include>
			</includes>
		</fileSet>
		<fileSet>
			<directory>${project.build.directory}/conf</directory>
			<outputDirectory>bin</outputDirectory>
			<includes>
				<include>airavata-server.properties</include>
				<include>zoo.cfg</include>
				<include>registry.properties</include>
				<include>log4j.properties</include>
				<include>host.xml</include>
				<include>persistence.xml</include>
				<include>provenance.sql</include>
				<include>gfac-config.xml</include>
				<include>PBSTemplate.xslt</include>
				<include>SLURMTemplate.xslt</include>
				<include>SGETemplate.xslt</include>
				<include>gsissh.properties</include>
			</includes>
		</fileSet>

		<!-- ********************** Copy Axis2 startup scripts to stand alone server 
			********************** -->
		<fileSet>
			<directory>src/main/resources/axis2-standalone-bin</directory>
			<outputDirectory>bin</outputDirectory>
			<fileMode>777</fileMode>
			<includes>
				<include>*.sh</include>
				<include>*.bat</include>
			</includes>
		</fileSet>

		<fileSet>
			<directory>src/main/resources/conf</directory>
			<outputDirectory>bin</outputDirectory>
			<includes>
				<include>**/*</include>
			</includes>
		</fileSet>

		<!-- ********************** Copy samples ********************** -->
		<fileSet>
			<directory>${project.build.directory}/samples/applications
			</directory>
			<outputDirectory>samples</outputDirectory>
			<includes>
				<include>*.sh</include>
				<include>*.bat</include>
			</includes>
		</fileSet>

	</fileSets>

	<dependencySets>
		<dependencySet>
			<outputDirectory>lib</outputDirectory>
			<outputFileNameMapping>${artifact.artifactId}.${artifact.extension}
			</outputFileNameMapping>
			<includes>
				<include>org.apache.derby:derby:jar</include>
				<include>org.apache.derby:derbytools:jar</include>
				<include>org.apache.derby:derbynet:jar</include>
				<include>org.apache.derby:derbyclient:jar</include>
			</includes>
		</dependencySet>
		<dependencySet>
			<outputDirectory>lib</outputDirectory>
			<includes>
				<include>org.slf4j:slf4j-api:jar</include>
				<include>org.slf4j:slf4j-jcl:jar</include>
				<include>org.slf4j:slf4j-log4j12:jar</include>
				<include>log4j:log4j:jar</include>
				<include>javax.jcr:jcr:jar</include>
				<include>commons-collections:commons-collections</include>
				<include>commons-configuration:commons-configuration</include>
				<include>commons-lang:commons-lang</include>
				<include>commons-io:commons-io</include>
				<include>org.ogce:xpp3:jar</include>
				<include>org.ogce:xpp5:jar</include>
				<include>org.ogce:xsul:jar</include>
				<include>org.ogce:xsul5:jar</include>
				<include>org.ogce:gpel-client:jar</include>
				<include>org.ogce:atomixmiser:jar</include>
				<include>org.ogce:yfilter:jar</include>
				<include>org.python:jython:jar</include>
				<include>org.jglobus:gss</include>
				<include>org.jglobus:gram</include>
				<include>org.jglobus:myproxy</include>
				<include>org.jglobus:gridftp</include>
				<include>org.jglobus:ssl-proxies</include>
				<include>org.jglobus:jsse</include>
				<include>org.jglobus:io</include>
				<include>org.jglobus:axis</include>
				<include>org.apache.xmlbeans:xmlbeans</include>
				<include>com.amazonaws:aws-java-sdk</include>
				<include>net.java.dev.jets3t:jets3t</include>
				<include>org.apache.airavata:airavata-standalone-server:jar
				</include>
				<include>org.apache.airavata:airavata-common-utils:jar</include>
				<include>org.apache.airavata:airavata-orchestrator-service:jar
				</include>
				<include>org.apache.airavata:airavata-orchestrator-core:jar
				</include>
				<include>org.apache.airavata:airavata-gfac-schema-utils:jar
				</include>
				<include>org.apache.airavata:airavata-workflow-execution-context:jar
				</include>
				<include>org.apache.airavata:airavata-registry-cpi:jar</include>
				<include>org.apache.airavata:airavata-jpa-registry:jar</include>
				<include>org.apache.airavata:app-catalog-cpi:jar</include>
				<include>org.apache.airavata:app-catalog-data:jar</include>
				<include>org.apache.airavata:airavata-data-models:jar</include>
				<include>org.apache.airavata:airavata-credential-store:jar</include>
				<include>org.apache.airavata:airavata-gfac-core:jar</include>
				<include>org.apache.airavata:airavata-gfac-service:jar</include>
				<include>org.apache.airavata:airavata-gfac-ssh:jar</include>
				<include>org.apache.airavata:airavata-gfac-local:jar</include>
				<include>org.apache.airavata:airavata-gfac-gsissh:jar</include>
				<include>org.apache.airavata:airavata-gfac-hpc-monitor:jar</include>
				<include>org.apache.airavata:airavata-gfac-hadoop:jar</include>
				<include>org.apache.airavata:airavata-gfac-bes:jar</include>
				<include>org.apache.airavata:airavata-gfac-gram:jar</include>
				<include>org.apache.airavata:airavata-message-monitor:jar</include>
				<include>org.apache.airavata:airavata-workflow-model-core:jar
				</include>
				<include>org.apache.airavata:airavata-messenger-commons:jar
				</include>
				<include>org.apache.airavata:airavata-messenger-client:jar</include>
				<include>org.apache.airavata:airavata-workflow-tracking:jar
				</include>
				<include>org.apache.airavata:airavata-workflow-engine:jar</include>
				<include>org.apache.airavata:airavata-messaging-core:jar</include>
				<include>org.apache.airavata:gsissh:jar</include>
				<include>org.apache.airavata:airavata-model-utils:jar</include>
				<include>org.apache.airavata:airavata-api-server:jar</include>
				<include>org.apache.airavata:airavata-api-stubs:jar</include>
				<include>org.apache.openjpa:openjpa-all:jar</include>
				<include>org.bouncycastle:bcprov-jdk15on</include>
				<include>javax.servlet:javax.servlet-api</include>
				<include>xerces:xercesImpl:jar:2.9.1</include>
				<include>com.ibm.icu:icu4j</include>
				<include>com.google.guava:guava</include>
				<include>org.apache.hadoop:hadoop-core</include>
				<include>org.apache.hadoop:hadoop-client</include>
				<include>org.apache.whirr:whirr-hadoop</include>
				<include>org.hamcrest:hamcrest-all</include>
				<include>org.mockito:mockito-all</include>
				<include>com.jcraft:jsch</include>
				<include>net.sf.jopt-simple:jopt-simple</include>
				<include>net.schmizz:sshj</include>
				<include>j2ssh:j2ssh-core</include>
				<include>j2ssh:j2ssh-common</include>
				<include>org.apache.httpcomponents:httpcore:jar:4.1</include>
				<include>org.apache.httpcomponents:httpclient:jar:4.1</include>
				<include>de.odysseus.staxon:staxon:jar:1.2</include>
				<include>de.odysseus.staxon:staxon-jackson:jar:1.2</include>
				<include>org.ebaysf.web:cors-filter:jar:1.0.0</include>
				<include>org.ogce:bcgss</include>
				<include>org.apache.xmlbeans:xmlbeans</include>
				<include>org.apache.thrift:libthrift:jar:0.9.1</include>
				<include>commons-cli:commons-cli</include>
				<include>commons-codec:commons-codec</include>
				<include>com.rabbitmq:amqp-client</include>
				<include>com.fasterxml.jackson.core:jackson-databind</include>
				<include>com.fasterxml.jackson.core:jackson-core</include>
				<include>com.fasterxml.jackson.core:jackson-annotations</include>
				<include>org.apache.zookeeper:zookeeper</include>

				<!-- UNICORE Dependencies Start -->
				<include>org.apache.xmlbeans:xmlbeans-xpath</include>
				<include>net.sf.saxon:saxon</include>
				<include>net.sf.saxon:saxon-dom</include>
				<include>net.sf.saxon:saxon-xpath</include>
				<include>log4j:apache-log4j-extras</include>
				<include>eu.eu-emi.security:canl</include>
				<include>org.bouncycastle:bcpkix-jdk15on</include>
				<include>pl.edu.icm.saml:samly2</include>
				<include>org.apache.ws.security:wss4j</include>
				<include>org.json:json</include>
				<include>org.apache.cxf:cxf-rt-databinding-xmlbeans</include>
				<include>org.apache.cxf:cxf-api</include>
				<include>org.codehaus.woodstox:woodstox-core-asl</include>
				<include>org.codehaus.woodstox:stax2-api</include>
				<include>org.apache.ws.xmlschema:xmlschema-core</include>
				<include>org.apache.cxf:cxf-rt-core</include>
				<include>com.sun.xml.bind:jaxb-impl</include>
				<include>org.apache.cxf:cxf-rt-frontend-jaxws</include>
				<include>xml-resolver:xml-resolver</include>
				<include>asm:asm</include>
				<include>org.apache.cxf:cxf-rt-bindings-soap</include>
				<include>org.apache.cxf:cxf-rt-databinding-jaxb</include>
				<include>org.apache.cxf:cxf-rt-bindings-xml</include>
				<include>org.apache.cxf:cxf-rt-frontend-simple</include>
				<include>org.apache.cxf:cxf-rt-ws-addr</include>
				<include>org.apache.cxf:cxf-rt-ws-policy</include>
				<include>org.apache.cxf:cxf-rt-transports-http</include>
				<include>org.apache.cxf:cxf-rt-features-clustering</include>
				<!-- UNICORE Dependencies End -->
			</includes>
		</dependencySet>

	</dependencySets>

</assembly>
